### ISSUE TITLE
SoapPy Error On Connect

### ISSUE THREAD

**Issue by sauditore** [sauditore/Python-Mellat#1]
API init fails when trying to connect to web service.

**Comment by miladebadi** [comment]
same here:
'_ssl._SSLSocket' object has no attribute 'sendall'

**Comment by sauditore** [comment]
I will Patch this ASAP. The problem is in wstools.py. will fix it soon

**Comment by sauditore** [comment]
[SOAPPY Bug](https://github.com/sauditore/Python-Mellat/wiki/Bug-In-SOAPPY)
Please check and confirm ;)

**Comment by miladebadi** [comment]
I solved the problem by migrating from soapy to suds (https://pypi.python.org/pypi/suds) It is really easy to integrate with your library. I will send a pull request tommorow , if you want you can consider it. By the way, the problem is Mellat bank uses a not well-formed ssl which causes the issue with soapy and their returned xml responce from web service is not also well-formed which makes us to deal with another issue. I decided to use suds because it has also importdoctor which can fix xml problems.

**Comment by sauditore** [comment]
Then i will thank you for your solution. 
After merging your pull request i will fix it on pypy too.

**Comment by miladebadi** [comment]
You are welcome, please test it, if everything works fine you can close this issue, also do not forget to add suds to the requirements of this package
